dist: trusty
env:
  TERM=dumb

install: true
language: scala
scala:
  - 2.12.3
script:
  #- pushd src/test/resources
  #- git clone https://github.com/xproc/3.0-test-suite.git test-suite
  #- popd
  - sbt ++$TRAVIS_SCALA_VERSION test
sudu: false
jdk:
  - oraclejdk8

#after_success:
#  - src/website/bin/travis-publish.sh
